***NumPy - Numerical Python***

***Advantages of Numpy Arrays:**

1.   Allow several Mathematical operations
2.   Faster operations



In [ ]:
# Importing
import numpy as np

***List vs Numpy : Time taken***

In [ ]:
from time import process_time

*Time taken by list*

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007844779999999218


In [ ]:
# Time taken by arrays
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.00019019600000014236


***Numpy Array***

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


***Initial placeholders in numpy array***

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.53632834 0.43787258 0.22289955 0.34543602]
 [0.9692205  0.55808451 0.01833323 0.43664662]
 [0.42855137 0.62506783 0.91147135 0.62091226]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[55 95 42 85 67]
 [96 92 95 26 76]
 [27 98 45 78 85]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

***Analysis a numpy array***

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[61 16 70 71 15]
 [30 57 65 74 52]
 [84 26 37 27 43]
 [79 22 86 64 41]
 [47 15 81 67 80]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


***Mathematical operations on numpy array***

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)

print(b)

[[1 9 5]
 [1 2 8]
 [1 2 9]]
[[17 19 19]
 [18 19 11]
 [13 19 14]]


In [ ]:
# Basic arithmetic operations on array
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 28 24]
 [19 21 19]
 [14 21 23]]
[[-16 -10 -14]
 [-17 -17  -3]
 [-12 -17  -5]]
[[ 17 171  95]
 [ 18  38  88]
 [ 13  38 126]]
[[0.05882353 0.47368421 0.26315789]
 [0.05555556 0.10526316 0.72727273]
 [0.07692308 0.10526316 0.64285714]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[9 2 6]
 [8 9 5]
 [4 3 3]]
[[18 12 16]
 [12 18 10]
 [15 18 19]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[27 14 22]
 [20 27 15]
 [19 21 22]]
[[ -9 -10 -10]
 [ -4  -9  -5]
 [-11 -15 -16]]
[[162  24  96]
 [ 96 162  50]
 [ 60  54  57]]
[[0.5        0.16666667 0.375     ]
 [0.66666667 0.5        0.5       ]
 [0.26666667 0.16666667 0.15789474]]


***Array Manipulation***

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 4 6]
 [6 2 7]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 6]
 [4 2]
 [6 7]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 9 8]
 [7 1 5]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 7]
 [9 1]
 [8 5]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 2 3]
 [8 1 2]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 2]
 [3 8]
 [1 2]]
(3, 2)
